// This code runs on the SERVER, so your API key is safe.
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  try {
    // 1. Get the user stats from the frontend request body
    const {
      score,
      maxScore,
      percentage,
      accuracy,
      attempted,
      totalQuestions,
      attemptRate,
      correct,
      incorrect,
      unanswered,
      avgTimePerQuestion,
      timeTaken,
      positiveMarking,
      negativeMarking,
    } = req.body;

    // 2. Use the API key securely from server-side environment variables
    // IMPORTANT: Your .env.local file should now have GEMINI_KEY="..." (NO "NEXT_PUBLIC_")
    const GEMINI_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_KEY) {
      throw new Error("API key is not configured on the server.");
    }

    // 3. A better, more structured prompt for the AI
    const prompt = `
      You are an expert exam preparation coach.
      Your task is to generate 5 personalized, concise, and actionable tips for a user based on their recent exam performance.

      Here are the user's stats:
      - Score: ${score} out of ${maxScore} (${percentage.toFixed(1)}%)
      - Accuracy (on attempted questions): ${accuracy.toFixed(1)}%
      - Attempt Rate: ${attempted} out of ${totalQuestions} questions (${attemptRate}%)
      - Breakdown: ${correct} correct, ${incorrect} incorrect, ${unanswered} unanswered.
      - Time Management: ${avgTimePerQuestion}s avg. time per question, ${timeTaken} total time.
      - Marking Scheme: +${positiveMarking} for correct, -${negativeMarking} for incorrect.

      Analyze these stats to identify the user's main weaknesses (e.g., low accuracy, poor time management, high number of unanswered questions, impact of negative marking).
      Generate encouraging and practical tips to address these specific weaknesses.

      IMPORTANT: Return the response as a JSON array of strings. For example: ["Tip 1", "Tip 2", "Tip 3", "Tip 4", "Tip 5"]
    `;

    // 4. Call the Gemini API
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${GEMINI_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        // Add safety settings and generation config for better control
        generationConfig: {
            responseMimeType: "application/json", // Ask for JSON directly!
            temperature: 0.7,
        }
      }),
    });

    if (!response.ok) {
      // If Google's API returns an error, log it and send a generic server error
      const errorData = await response.json();
      console.error('Gemini API Error:', errorData);
      throw new Error('Failed to fetch tips from the AI model.');
    }

    const data = await response.json();

    // 5. Robustly parse the response
    const generatedText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
      throw new Error('No content generated by the AI model.');
    }
    
    // The AI should return a JSON string, so we parse it.
    const tips = JSON.parse(generatedText);

    // 6. Send the successful response back to the frontend
    res.status(200).json({ tips });

  } catch (error) {
    console.error('API Route Error:', error.message);
    res.status(500).json({ message: 'An internal server error occurred.' });
  }
}